version: "3.8"

#  Stack IoT — TP1 UFHB M1 BDGL
#  Services : Mosquitto · Telegraf · InfluxDB · Grafana

networks:
  iot_network:
    driver: bridge

volumes:
  influxdb_data:
  influxdb_config:
  grafana_data:
  mosquitto_data:
  mosquitto_log:

services:

  # ----------------------------------------------------------
  #  1. MOSQUITTO — Broker MQTT
  #     Port MQTT : 1883
  #     Port WebSocket : 9001
  # ----------------------------------------------------------
  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
    networks:
      - iot_network

  # ----------------------------------------------------------
  #  2. INFLUXDB — Base de données time-series
  #     UI Web : http://localhost:8086
  #     Login  : admin / ufhb2024!
  # ----------------------------------------------------------
  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    restart: unless-stopped
    ports:
      - "8086:8086"
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: ufhb2024!
      DOCKER_INFLUXDB_INIT_ORG: UFHB-IoT
      DOCKER_INFLUXDB_INIT_BUCKET: raw_7d
      DOCKER_INFLUXDB_INIT_RETENTION: 168h
    volumes:
      - influxdb_data:/var/lib/influxdb2
      - influxdb_config:/etc/influxdb2
    networks:
      - iot_network

  # ----------------------------------------------------------
  #  3. GRAFANA — Dashboards de visualisation
  #     UI Web : http://localhost:3000
  #     Login  : admin / ufhb2024!
  # ----------------------------------------------------------
  grafana:
    image: grafana/grafana:10.4.0
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: ufhb2024!
      GF_INSTALL_PLUGINS: grafana-clock-panel,grafana-simple-json-datasource
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
    depends_on:
      - influxdb
    networks:
      - iot_network

  # ----------------------------------------------------------
  #  4. TELEGRAF — Agent de collecte MQTT → InfluxDB
  #     Souscrit à iot/CI/abidjan/# et écrit dans raw_7d
  #     Config : ./telegraf/telegraf.conf
  # ----------------------------------------------------------
  telegraf:
    image: telegraf:1.28
    container_name: telegraf
    restart: unless-stopped
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - mosquitto
      - influxdb
    networks:
      - iot_network