; PlatformIO Project Configuration File
; ESP32 + Wokwi Simulator
; M1 BDGL - UFHB IoT Stack

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; Bibliothèques nécessaires
lib_deps =
    knolleary/PubSubClient@^2.8
    adafruit/DHT sensor library@^1.4.6
    adafruit/Adafruit Unified Sensor@^1.1.14

; Configuration du moniteur série
monitor_speed = 115200

; Configuration Wokwi
board_build.mcu = esp32
board_build.f_cpu = 240000000L
