# =============================================================
#  Telegraf — Agent de collecte IoT
#  Pipeline : Mosquitto (MQTT) → InfluxDB 2.x
#  TP1 IoT M1 BDGL — UFHB
# =============================================================

[agent]
  interval       = "10s"
  flush_interval = "10s"
  omit_hostname  = false

# -------------------------------------------------------------
#  OUTPUT → InfluxDB 2.x
#  ⚠ Remplacer YOUR_TOKEN par le token généré dans l'UI InfluxDB
#  InfluxDB UI → Load Data → API Tokens → Generate API Token
# -------------------------------------------------------------
[[outputs.influxdb_v2]]
  urls         = ["http://influxdb:8086"]
  token        = "w0y2oNesnnAFM2g6NKGkib1PBYnpRsZ-BVLOJOkMUbB7sbTrewHTn3viC0xFsGfId1x891U6CPFdjctHUmEDng=="
  organization = "UFHB-IoT"
  bucket       = "raw_7d"

# -------------------------------------------------------------
#  INPUT → MQTT Consumer (Mosquitto)
#  data_format = "influx" → attend le Line Protocol
#  Format payload ESP32 :
#  environment,location=cocody,device_id=ESP32_001,sensor=DHT22 temperature=27.5,humidity=62.3
# -------------------------------------------------------------
[[inputs.mqtt_consumer]]
  servers = ["tcp://mosquitto:1883"]

  topics = [
    "iot/CI/abidjan/#"
  ]

  # Line Protocol : Telegraf comprend directement le format InfluxDB
  # Pas besoin de topic_parsing — les tags sont dans le payload
  data_format = "influx"